### PR TITLE
Fix Jenkinsfile

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Very very related to #345, right @pragmaticivan ?

**Comment by pragmaticivan** [comment]
@mdelapenya yes, I was working on that, you can take over if you want

**Comment by zenorocha** [comment]
Should I review this one or #345?

**Comment by pragmaticivan** [comment]
Just this PR for noe @zenorocha, #345 is only for tests purpose.

**Comment by mdelapenya** [comment]
Yes @zenorocha, please review it to fix the build pipeline in Jenkins

Thanks!

**Pull request merged**
