### PR TITLE
Update docs with latest DXP version (Resolves #375)

### LINKED ISSUE #375: Upgrade DXP version
Depends on https://github.com/wedeploy/api/pull/605

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Let's not merge this PR until the version of repository of the DXP image is updated.

Thanks!

**Comment by zenorocha** [comment]
Let us know when it's ready @mdelapenya ;)

**Comment by mdelapenya** [comment]
Hey team, this can be merged, as image and api repos have been updated

Thanks!

**Comment by jonnilundy** [comment]
@mdelapenya @zenorocha Is this ready to merge. We are cleaning up PRs this week! 💪

**Comment by mdelapenya** [comment]
Yes, it's ready. DXP image has been merged into `api` project and a Docker image has been pushed to Docker Hub

**Pull request closed without merging**
