### PR TITLE
Add blog post about HTTP/2

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Okay, @eduardolundgren, I rephrased the last paragraph and this fact will be explicitly told now :)

**Comment by jonnilundy** [comment]
Reviewing now! :)

**Comment by jonnilundy** [comment]
Thanks, @ipeychev! Great post!

**Comment by ipeychev** [comment]
@jonnilundy Thanks :)
I sent another [PR](https://github.com/wedeploy/wedeploy.com/pull/377) to update the date, since when I wrote it was November 23-rd, but now it is November 27th :)

**Pull request merged**
