### PR TITLE
update CLI command

### PR DESCRIPTION
**Pull request by jonnilundy**

### CODE REVIEW

**Comment by zenorocha** [comment]
@henvic is this change on the stable channel already?

**Comment by pragmaticivan** [comment]
I don't think it's on stable channel. I was using the previous version yesterday.

**Comment by henvic** [comment]
@zenorocha, nope. It's not.

**Comment by zenorocha** [comment]
So we need to revert it @jonnilundy and only update when it's available for everybody.

**Comment by jonnilundy** [comment]
When are we planning to release this? @eduardolundgren and I had thought maybe by the time we review and release/promote the tutorials, it might align with the release of the new CLI.

**Pull request merged**
