### PR TITLE
Adds new branding screenshots

### PR DESCRIPTION
**Pull request by jonnilundy**

### CODE REVIEW

**Comment by vitorfernandes** [comment]
where?

**Comment by jonnilundy** [comment]
@vitorfernandes 
https://wedeploy.com/docs/intro/using-the-console/
https://wedeploy.com/docs/intro/custom-domains/
https://wedeploy.com/docs/intro/environment-variables/
https://wedeploy.com/docs/auth/sign-in-with-facebook/
https://wedeploy.com/docs/auth/sign-in-with-google/
https://wedeploy.com/docs/auth/sign-in-with-github/

**Comment by vitorfernandes** [comment]
Got it, let me know in case you need help.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
