### PR TITLE
Document get all users delete user new

### PR DESCRIPTION
**Pull request by NolanChan**
Redoing the PR since the beta-updates branch was closed.

@sgosantos and @victorg1991 , could you help me with the java and swift docs for `getAllUsers`? You can just paste the code documentation in here and I'll update the PR. Thanks! 😁

### CODE REVIEW

**Comment by jonnilundy** [comment]
@sgosantos @victorg1991  How is the progress on this?

**Comment by victorg1991** [comment]
Hey! Sorry for the delay, I was on vacation :)

This is the swift code for document both functions:

Delete users:

```WeDeploy
			.auth("https://<serviceID>.<projectID>.wedeploy.io")
			.deleteUser(id: "userId")
			.then { _ -> Void in
				// Successfully deleted.
			}
			.catch { error in
				// An error happened.
			}```

Get all users:

```WeDeploy
			.auth("https://<serviceID>.<projectID>.wedeploy.io")
			.getAllUsers()
			.then { res -> Void in
				// res contains an array of users.
			}
			.catch { error in
				// An error happened.
			}```

**Comment by zenorocha** [comment]
Thanks @victorg1991!

**Comment by sgosantos** [comment]
Sorry for the delay. I've seen the delete is already there, but I'm sending again.
I've also noticed that the URL pattern for the java samples is different from Javascript and Swift ones. Did you guys update that?

**Delete User**
```
WeDeploy
	.auth("https://<serviceID>-<projectID>.wedeploy.io")
	.deleteUser("userId")
	.execute();
```

**Get All Users**
```
WeDeploy
	.auth("https://<serviceID>-<projectID>.wedeploy.io")
	.getAllUsers()
	.execute();
```

**Comment by zenorocha** [comment]
Thanks @sgosantos!

@jonnilundy you can now merge and include this.

**Comment by jonnilundy** [comment]
@sgosantos @victorg1991 Added your code here: 5e7d2af.

Thanks again!!

**Pull request merged**
