### PR TITLE
Removes target _blank from pricing link

### PR DESCRIPTION
**Pull request by jonnilundy**
Having the pricing page open up in a separate tab feels very strange since it is navigating to the homepage.

### CODE REVIEW

**Comment by jonnilundy** [comment]
@zenorocha any other feedback on this before merging?

**Comment by zenorocha** [comment]
I'm not sure if we can merge this because of Senna. Can you deploy and test if it works?

**Comment by jonnilundy** [comment]
@zenorocha Updated with the fix. I had to add the special senna exception for `/#pricing`.

**Comment by pragmaticivan** [comment]
hey @jonnilundy can you try using `data-senna-off="true"` in the link instead of using that in the entire document? Thanks!

**Comment by jonnilundy** [comment]
@pragmaticivan Unfortunately we have already tried that and it still doesn't work. This was the only workaround that @zenorocha and I found to work.

**Comment by pragmaticivan** [comment]
All good, do you think we can merge like that so @zenorocha ?

**Pull request merged**
