### PR TITLE
Updates data parameter types

### PR DESCRIPTION
**Pull request by jonnilundy**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Hey @jonnilundy, did you have a chance to test if all those values work as expected?

**Comment by jonnilundy** [comment]
No, I was just trusting [this snippet](https://github.com/wedeploy/engine/blob/master/core/src/main/java/com/wedeploy/engine/core/ApiInputValue.java#L85). I can test more sometime this week.

**Comment by jonnilundy** [comment]
Asking @albertmourato to test for me when he has time.

**Comment by albertmourato** [comment]
@jonnilundy just checked here and all types are ok:

```javascript
weData
  .auth(currentUser)
  .create('tasks', {
    "name": "Tinna", 
    "age": 22, 
    "married": false, 
    "family": ["father", "mother", "sister", "brother"], 
    "address": {
      "city": "Serra Talhada", 
      "state": "Pernambuco", 
      "country":"Brazil"}
    })
```

And I got:

screen shot 2018-06-01 at 6 39 50 pm

**Comment by zenorocha** [comment]
Thank you so much @albertmourato for testing each type!

**Pull request merged**
