### PR TITLE
Update WeDeploy JS API to 3.0.2

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by jonnilundy** [comment]
LGTM

Is there some other way we should be "notifying" users of version releases besides just updating the docs? Like if there was a cli tool would list or something. I don't know what is common for other organizations to do.

**Comment by ipeychev** [comment]
Hey @jonnilundy,

In general, these channels are:
1. Announcements - Tweeter, Facebook, etc.
2. Blog posts - especially in case of major feature releases
3. For some packages and especially CLI tools there might be hints - for example when you run the package, it says: "There is a new version available, type 'npm update -g package-x' to update". Maybe @henvic may consider that for WeDeploy CLI.

Thanks,

**Comment by henvic** [comment]
> Is there some other way we should be "notifying" users of version releases besides just updating the docs?
As a user of a library package I usually don't want to be bothered just because the vendor decided to draft a new release. Unless it is a security advisory.

I could add a command of  `we list` flag on the CLI to check versions of used Docker images maintained by WeDeploy. Also, I could notify about security advisories on normal usage.

As for notifying about changes on the CLI tool itself, it already does so every other day.

**Comment by jonnilundy** [comment]
@henvic I like this idea. So to clarify, you could check the image versions but not the api client version?

**Pull request closed without merging**
