### PR TITLE
Revamp Data docs

### PR DESCRIPTION
**Pull request by jonnilundy**
#### PROGRESS
Follow the progress live: https://datadocs.wedeploy.io/docs/data/getting-started/
- [x] Document all filter types
- [x] General improvements across all data doc pages
- [x] Move all filtering sections to new filter page
- [x] Test all JavaScript code on new infrastructure
- [x] Supported Data types (#160)

#### BEFORE MERGING

- [x] Add Swift and Android code examples (@victorg1991 and @victorlaerte) Thanks!
- [x] Final review of Swift and Android code examples (@victorg1991 and @victorlaerte)

### CODE REVIEW

**Comment by victorg1991** [comment]
Can you elaborate this? 'Add Swift and Android code examples'
What do we have to do exactly? :)

Thanks!

**Comment by jonnilundy** [comment]
@victorg1991 Hey! I was hoping you could help add mobile docs on the new Filtering Data page in this PR.

**Comment by victorg1991** [comment]
@jonnilundy Nice, I'll do it :D 
Thanks!

**Comment by jonnilundy** [comment]
Hey @victorg1991 and @victorlaerte! I made some more updates to the data docs (especially on Real Time Data). Please review the Swift and Android code examples to verify that they are correct. Thank you!

I did not make code changes on the Filtering Data page, but all other pages have changes.

**Comment by victorlaerte** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorlaerte** [comment]
I have added a new PR with some minor fixes #396

**Comment by pragmaticivan** [comment]
hey @jonnilundy what's the conclusion of that one?

**Comment by jonnilundy** [comment]
@pragmaticivan Waiting for a final review/merge from @zenorocha.

**Pull request merged**
