### PR TITLE
Add documentation about sign-in with OAuth

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by jonnilundy** [comment]
Reviewing now! :)

**Comment by pragmaticivan** [comment]
Hey, what's the conclusion of that PR? @jonnilundy ?

**Comment by jonnilundy** [comment]
@ipeychev @pragmaticivan Since it is very old, it needs to be adapted (at least to meet the new structure of the docs file system). Is this something you are willing to do, Iliyan?

The primary change is that `ui/src/pages/docs/auth/sign-in-with-facebook.md` changed to `ui/src/pages/docs/auth/sign-in-with-facebook/index.md`

**Comment by ipeychev** [comment]
@jonnilundy Since it is only restructuring and it doesn't require updating the content, it would be better if you do it.

**Comment by jonnilundy** [comment]
Hey @ipeychev, because of how in depth, and niche this documentation is, we are wanting to move it to the Help Center. I have already pasted the content over there in [an article](https://app.intercom.io/a/apps/ocvh9014/educate/articles/1476695/show), so please review and set live when you feel it is ready. Thanks!

**Comment by ipeychev** [comment]
Hey @jonnilundy, it might be in Help center too. The article is almost OK - meanwhile ReactNative changed the way custm URL scheme is generated and this part has to be updated. It will take me some time to discover the new way and once I verify everything, I will publish it.

**Pull request closed without merging**
