### PR TITLE
Improving instructions on 'installing CLI'.

### PR DESCRIPTION
**Pull request by henvic**
Information lost when the repo was changed.

Imported from https://github.com/wedeploy/docs/commit/155a5c5a8621b0762a973db8ba1f5d5afca4be58

### CODE REVIEW

**Comment by jonnilundy** [comment]
@henvic Should we specify an oldest compatible version of git that users should have?

**Comment by henvic** [comment]
@jonnilundy I tested with 1.9.1 (March 18, 2014) and it works and I guess it works fine with way older versions, though I haven't tested. I think there's no need to do so.

**Comment by jonnilundy** [comment]
@henvic Even on Windows? I thought updated Git was a solution to the CLI issues?

**Comment by henvic** [comment]
On Windows the earliest I tested was version 2.5.0, July 27, 2015 (the oldest package I found, except from one pre-release a month or two before).

**Comment by henvic** [comment]
Updating git was a solution for our git invalid authentication issue. Now you can just update the we CLI tool (but updating git is still recommended).

**Comment by zenorocha** [comment]
Hey @henvic, can you fix the conflict and re-send the PR? Thanks!

**Comment by jonnilundy** [comment]
Hey @henvic! Do you think you could re-submit this PR so it can be merged by the end of the week? Let us know if we can help. Thanks!

**Pull request merged**
