### PR TITLE
Improve bubble performance on landing

### PR DESCRIPTION
**Pull request by jonathantneal**
The bubble animation slow down my machine. By not activating the bubble animation until the bubbles are visible, this greatly improved my initial experience.

### CODE REVIEW

**Comment by jonnilundy** [comment]
@zenorocha @jonathantneal Any other pending changes or feedback on this before we can merge?

**Comment by zenorocha** [comment]
@eduardolundgren would be the best person to review this since he helped to write this part of the code.

**Comment by jonnilundy** [comment]
@eduardolundgren If you have a second, could you take a look at this?

**Comment by eduardolundgren** [comment]
Delaying the animation start looks fine, the part it's not clear from this pull request is the top + undefined manipulation.

I would close this pull and simplify it by adding only a delay factor for initializing the bubbles.

**Comment by jonnilundy** [comment]
I'm going to close this from inactivity. We can reopen later if interested.

**Pull request closed without merging**
