### PR TITLE
Adds temporary blog homepage

### PR DESCRIPTION
**Pull request by jonnilundy**
We are currently losing any trace of blog posts further than 4 in the past. To fix this immediately until we have a full design from @vitorfernandes, here is a temporary fix.

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
1. Topbar link to "Blog" should direct to `/blog` instead of `/blog/latest-blogpost`
2. Topbar background should match the rest of the page background

screen shot 2017-11-29 at 9 37 47 am

**Comment by jonnilundy** [comment]
@zenorocha I can't find where electric is rendering the blog URL with the latest blog post. Is that in base components or maybe Marble?

**Comment by pragmaticivan** [comment]
Any progress here @jonnilundy ? is that still required?

**Comment by jonnilundy** [comment]
I was unable to find where the blog redirect is to change it to `/blog` instead of `/blog/latest-post`.

**Comment by zenorocha** [comment]
Closing now that @vitorfernandes will design a new one: https://github.com/wedeploy/wedeploy.com/issues/410

**Comment by zenorocha** [comment]
Reopening since the redesign will take a little.

**Pull request merged**
