### PR TITLE
Mobile blog post

### PR DESCRIPTION
**Pull request by jmnavarro**
Hey @zenorocha ready to review!

@jonnilundy do you mind to review my poor English?

### CODE REVIEW

**Comment by jonnilundy** [comment]
Hey @jmnavarro! Thanks for writing this. At first perception, this post feels a little code heavy (almost like a tutorial instead of announcement). What would you think of limiting each section (How do I start, iOS, and Andriod) to 2-3 code examples and adding links to the tutorials so they can try it themselves?

**Comment by jmnavarro** [comment]
@jonnilundy let me know what you think

**Comment by jonnilundy** [comment]
@jmnavarro I finished the announcement post. [Here is a gist](https://gist.github.com/jonnilundy/c6388009af6157a18a0471c0646bab35) of the markdown and I will attach the new image as well. 

Notice the name change on your video. You will need to change the name of the video on your machine.

Let me know what you think and feel free to make tweaks as needed. 

post-11--0

**Comment by jmnavarro** [comment]
@jonnilundy cool! please, send your new commits to this PR and I'll make the final changes

**Comment by jonnilundy** [comment]
Merged!

**Comment by jmnavarro** [comment]
hey @jonnilundy ! remember that we still need to merge your changes and make some tweaks before publishing!

**Comment by jonnilundy** [comment]
Yes, I made those changes. 👍

**Pull request closed without merging**
