### PR TITLE
Update email service

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by jonnilundy** [comment]
hey @mdelapenya, thanks for the PR! 

Can we update the changelog as well?

**Comment by jonnilundy** [comment]
Thanks @mdelapenya. Are these images ready and published? I noticed they are on Docker Hub but wanted to make sure.

**Comment by mdelapenya** [comment]
Yes, they are published, and updated across internal projects

**Comment by jonnilundy** [comment]
Perfect. Also, the title says that we are only updating the email image but it is for data and auth as well?

**Pull request merged**
