### PR TITLE
Updates marble from v3.1.3 to v3.4.4 - Fixes #448

### LINKED ISSUE #448: Sidebar shadow is broken on docs homepage
screen shot 2018-02-28 at 3 05 27 pm

### PR DESCRIPTION
**Pull request by jaredgorski**
Closes #448.

### CODE REVIEW

**Comment by jonnilundy** [comment]
@jaredgorski Actually, just noticed something. It looks like there is a regression on the link button padding?

image

**Comment by jaredgorski** [comment]
@jonnilundy @ygorcosta 
Found this commit changing button styles recently: https://github.com/wedeploy/marble/commit/1634f0e1d95cdc6224b9fe66dff51654e5967935

@ygorcosta, what's the best way to fix this?

**Comment by jaredgorski** [comment]
@jonnilundy 

Just added two PRs to fix these.

1. Fixes the button in the topbar: https://github.com/wedeploy/marble/pull/97
2. Fixes the buttons in the docs: https://github.com/wedeploy/wedeploy.com/pull/545

**Comment by jonnilundy** [comment]
@jaredgorski Thanks for tracking down those changes. Since these PRs effect each other and we need them together to test to make sure it's working before merging into master, what do you think about making them one pr. All you would need to do is add the Marble update change to the other PR and it would be good.

**Pull request closed without merging**
