### PR TITLE
Create a blog post about React Native support

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey guys, here it is!
I couldn't see it as it will look at the end, so please check if the video is displayed, how does it look in general, etc.

Thanks!

@zenorocha @jonnilundy

**Comment by ipeychev** [comment]
Hey guys,

Here is the PR, with applied the recommended changes and without the build files.

Thanks for the help!

@zenorocha, @jonnilundy

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
And we're live! Thanks @ipeychev for making this happen ;)

http://wedeploy.com/blog/using-wedeploy-with-react-native-and-react-vr.html

**Comment by ipeychev** [comment]
Thank you, guys - for the help with editing and the wonderful image!

**Pull request closed without merging**
